[project]
name = "bbf-921"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datamodel-code-generator[http,ruff]>=0.58.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "*_config.py"]

[tool.ruff.lint]
per-file-ignores = { "src/api/schemas/models/*.py" = ["F821"], "src/api/schemas/generated.py" = ["F821"] }

[tool.coverage.run]
source = ["src"]
omit = ["src/api/schemas/models/*", "src/api/schemas/generated.py"]
