# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Addressable(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    """
    Hyperlink reference
    """
    id: str | None = None
    """
    unique identifier
    """


class AddressableMVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Common(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_id: Annotated[AnyUrl | None, Field(alias='@id')] = None
    """
    Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.
    """
    field_value: Annotated[str | None, Field(alias='@value')] = None
    """
    Used to specify the data that is associated with a particular property in the graph.
    """
    field_language: Annotated[str | None, Field(alias='@language')] = None
    """
    Used to specify the language for a particular string value or the default language of a JSON-LD document.
    """
    field_type: Annotated[str | None, Field(alias='@type')] = None
    """
    Used to set the data type of a node or typed value.
    """
    field_container: Annotated[FieldContainer | None, Field(alias='@container')] = None
    """
    Used to set the default container type for a term.
    """
    field_list: Annotated[Any | None, Field(alias='@list')] = None
    """
    Used to express an ordered set of data.
    """
    field_set: Annotated[Any | None, Field(alias='@set')] = None
    """
    Used to express an unordered set of data and to ensure that values are always represented as arrays.
    """
    field_reverse: Annotated[str | None, Field(alias='@reverse')] = None
    """
    Used to express reverse properties.
    """
    field_base: Annotated[AnyUrl | None, Field(alias='@base')] = None
    """
    Used to set the base IRI against which relative IRIs are resolved
    """
    field_vocab: Annotated[AnyUrl | None, Field(alias='@vocab')] = None
    """
    Used to expand properties and values in @type with a common prefix IRI
    """


class CommonFVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_id: Annotated[AnyUrl | None, Field(alias='@id')] = None
    """
    Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.
    """
    field_value: Annotated[str | None, Field(alias='@value')] = None
    """
    Used to specify the data that is associated with a particular property in the graph.
    """
    field_language: Annotated[str | None, Field(alias='@language')] = None
    """
    Used to specify the language for a particular string value or the default language of a JSON-LD document.
    """
    field_type: Annotated[str, Field(alias='@type')]
    """
    Used to set the data type of a node or typed value.
    """
    field_container: Annotated[FieldContainer | None, Field(alias='@container')] = None
    """
    Used to set the default container type for a term.
    """
    field_list: Annotated[Any | None, Field(alias='@list')] = None
    """
    Used to express an ordered set of data.
    """
    field_set: Annotated[Any | None, Field(alias='@set')] = None
    """
    Used to express an unordered set of data and to ensure that values are always represented as arrays.
    """
    field_reverse: Annotated[str | None, Field(alias='@reverse')] = None
    """
    Used to express reverse properties.
    """
    field_base: Annotated[AnyUrl | None, Field(alias='@base')] = None
    """
    Used to set the base IRI against which relative IRIs are resolved
    """
    field_vocab: Annotated[AnyUrl | None, Field(alias='@vocab')] = None
    """
    Used to expand properties and values in @type with a common prefix IRI
    """


class CommonMVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_id: Annotated[AnyUrl | None, Field(alias='@id')] = None
    """
    Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.
    """
    field_value: Annotated[str | None, Field(alias='@value')] = None
    """
    Used to specify the data that is associated with a particular property in the graph.
    """
    field_language: Annotated[str | None, Field(alias='@language')] = None
    """
    Used to specify the language for a particular string value or the default language of a JSON-LD document.
    """
    field_container: Annotated[FieldContainer | None, Field(alias='@container')] = None
    """
    Used to set the default container type for a term.
    """
    field_list: Annotated[Any | None, Field(alias='@list')] = None
    """
    Used to express an ordered set of data.
    """
    field_set: Annotated[Any | None, Field(alias='@set')] = None
    """
    Used to express an unordered set of data and to ensure that values are always represented as arrays.
    """
    field_reverse: Annotated[str | None, Field(alias='@reverse')] = None
    """
    Used to express reverse properties.
    """
    field_base: Annotated[AnyUrl | None, Field(alias='@base')] = None
    """
    Used to set the base IRI against which relative IRIs are resolved
    """
    field_vocab: Annotated[AnyUrl | None, Field(alias='@vocab')] = None
    """
    Used to expand properties and values in @type with a common prefix IRI
    """


class Context(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_context: Annotated[dict[str, Any] | None, Field(alias='@context')] = None
    """
    Used to define the short-hand names that are used throughout a JSON-LD document.
    """


class ContextFVO(Context):
    pass


class ContextMVO(Context):
    pass


class EntityRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Annotated[str, Field(alias='@type')]
    """
    When sub-classing, this defines the sub-class Extensible name
    """
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    """
    When sub-classing, this defines the super-class
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    href: str | None = None
    """
    The URI of the referred entity.
    """
    id: str
    """
    The identifier of the referred entity.
    """
    name: str | None = None
    """
    Name of the referred entity.
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
    """
    The actual type of the target instance when needed for disambiguation.
    """


class AttachmentRef(EntityRef):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A narrative text describing the content of the attachment
    """
    url: str | None = None
    """
    Link to the attachment media/content
    """


class ConstraintRef(EntityRef):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    version: str | None = None
    """
    constraint version
    """


class EntityRefFVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Annotated[str, Field(alias='@type')]
    """
    When sub-classing, this defines the sub-class Extensible name
    """
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    """
    When sub-classing, this defines the super-class
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    href: str | None = None
    """
    The URI of the referred entity.
    """
    id: str
    """
    The identifier of the referred entity.
    """
    name: str
    """
    Name of the referred entity.
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
    """
    The actual type of the target instance when needed for disambiguation.
    """


class AttachmentRefFVO(EntityRefFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A narrative text describing the content of the attachment
    """
    url: str | None = None
    """
    Link to the attachment media/content
    """


class ConstraintRefFVO(EntityRefFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    version: str | None = None
    """
    constraint version
    """


class EntityRelationship(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[EntityRef | None, Field(alias='associationSpec')] = None
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    """
    When sub-classing, this defines the super-class
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
    id: str | None = None
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
    field_type: Annotated[str | None, Field(alias='@type')] = None


class EntityRelationshipFVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[EntityRefFVO | None, Field(alias='associationSpec')] = (
        None
    )
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    """
    When sub-classing, this defines the super-class
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
    id: str
    field_referred_type: Annotated[str, Field(alias='@referredType')]
    field_type: Annotated[str, Field(alias='@type')]


class EntityRelationshipMVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[EntityRefMVO | None, Field(alias='associationSpec')] = (
        None
    )
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None


class EntitySpecificationRelationship(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity specification
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[
        AssociationSpecificationRef | None,
        Field(alias='associationSpec', discriminator='field_type'),
    ] = None
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """


class EntitySpecificationRelationshipFVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    name: str | None = None
    role: str
    """
    The association role for this entity specification
    """
    valid_for: Annotated[TimePeriod, Field(alias='validFor')]
    association_spec: Annotated[
        AssociationSpecificationRefFVO,
        Field(alias='associationSpec', discriminator='field_type'),
    ]
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """


class EntitySpecificationRelationshipMVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity specification
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[
        AssociationSpecificationRefMVO | None,
        Field(alias='associationSpec', discriminator='field_type'),
    ] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """


class Extensible(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Annotated[str, Field(alias='@type')]
    """
    When sub-classing, this defines the sub-class Extensible name
    """
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    """
    When sub-classing, this defines the super-class
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """


class Characteristic(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    name: str | None = None
    """
    Name of the characteristic
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    Data type of the value of the characteristic
    """
    characteristic_relationship: Annotated[
        list[CharacteristicRelationship] | None,
        Field(alias='characteristicRelationship'),
    ] = None


class BooleanArrayCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[bool] | None = None


class BooleanCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: bool | None = None
    """
    Value of the characteristic
    """


class CharacteristicRelationship(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    The type of relationship
    """


class CharacteristicSpecification(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique ID for the characteristic
    """
    name: str | None = None
    """
    A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic can take on, such as numeric, text and so forth
    """
    description: str | None = None
    """
    A narrative that explains the CharacteristicSpecification.
    """
    configurable: bool | None = None
    """
    If true, the Boolean indicates that the target Characteristic is configurable
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    min_cardinality: Annotated[int | None, Field(alias='minCardinality')] = None
    """
    The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.
    """
    max_cardinality: Annotated[int | None, Field(alias='maxCardinality')] = None
    """
    The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.
    """
    is_unique: Annotated[bool | None, Field(alias='isUnique')] = None
    """
    Specifies if the value of this characteristic is unique across all entities instantiated from the specification that uses this characteristc. For example, consider a ProductSpecification for a set-top box, with a CharacteristicSpecification cardID. Each set-top box must have a different value for cardID, so this isUnique attribute would be set to true for the characteristic.
    """
    regex: str | None = None
    """
    A rule or principle represented in regular expression used to derive the value of a characteristic value.
    """
    extensible: bool | None = None
    """
    An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.
    """
    field_value_schema_location: Annotated[
        str | None, Field(alias='@valueSchemaLocation')
    ] = None
    """
    This (optional) field provides a link to the schema describing the value type.
    """
    char_spec_relationship: Annotated[
        list[CharacteristicSpecificationRelationship] | None,
        Field(alias='charSpecRelationship'),
    ] = None
    """
    An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.
    """
    characteristic_value_specification: Annotated[
        list[CharacteristicValueSpecification] | None,
        Field(alias='characteristicValueSpecification'),
    ] = None
    """
    A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a CharacteristicSpecification object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding Characteristic object can take on.
    """


class CharacteristicSpecificationFVO(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique ID for the characteristic
    """
    name: str
    """
    A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.
    """
    value_type: Annotated[str, Field(alias='valueType')]
    """
    A kind of value that the characteristic can take on, such as numeric, text and so forth
    """
    description: str | None = None
    """
    A narrative that explains the CharacteristicSpecification.
    """
    configurable: bool | None = None
    """
    If true, the Boolean indicates that the target Characteristic is configurable
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    min_cardinality: Annotated[int | None, Field(alias='minCardinality')] = None
    """
    The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.
    """
    max_cardinality: Annotated[int | None, Field(alias='maxCardinality')] = None
    """
    The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.
    """
    is_unique: Annotated[bool | None, Field(alias='isUnique')] = None
    """
    Specifies if the value of this characteristic is unique across all entities instantiated from the specification that uses this characteristc. For example, consider a ProductSpecification for a set-top box, with a CharacteristicSpecification cardID. Each set-top box must have a different value for cardID, so this isUnique attribute would be set to true for the characteristic.
    """
    regex: str | None = None
    """
    A rule or principle represented in regular expression used to derive the value of a characteristic value.
    """
    extensible: bool | None = None
    """
    An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.
    """
    field_value_schema_location: Annotated[
        str | None, Field(alias='@valueSchemaLocation')
    ] = None
    """
    This (optional) field provides a link to the schema describing the value type.
    """
    char_spec_relationship: Annotated[
        list[CharacteristicSpecificationRelationshipFVO] | None,
        Field(alias='charSpecRelationship'),
    ] = None
    """
    An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.
    """
    characteristic_value_specification: Annotated[
        list[CharacteristicValueSpecification] | None,
        Field(alias='characteristicValueSpecification'),
    ] = None
    """
    A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a CharacteristicSpecification object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding Characteristic object can take on.
    """


class CharacteristicSpecificationRelationship(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as aggregation, migration, substitution, dependency, exclusivity
    """
    name: str | None = None
    """
    Name of the target characteristic within the specification
    """
    characteristic_specification_id: Annotated[
        str | None, Field(alias='characteristicSpecificationId')
    ] = None
    """
    Unique identifier of the characteristic within the specification
    """
    parent_specification_href: Annotated[
        AnyUrl | None, Field(alias='parentSpecificationHref')
    ] = None
    """
    Hyperlink reference to the parent specification containing the target characteristic
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    parent_specification_id: Annotated[
        str | None, Field(alias='parentSpecificationId')
    ] = None
    """
    Unique identifier of the parent specification containing the target characteristic
    """


class CharacteristicSpecificationRelationshipFVO(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as aggregation, migration, substitution, dependency, exclusivity
    """
    name: str
    """
    Name of the target characteristic within the specification
    """
    characteristic_specification_id: Annotated[
        str | None, Field(alias='characteristicSpecificationId')
    ] = None
    """
    Unique identifier of the characteristic within the specification
    """
    parent_specification_href: Annotated[
        AnyUrl | None, Field(alias='parentSpecificationHref')
    ] = None
    """
    Hyperlink reference to the parent specification containing the target characteristic
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    parent_specification_id: Annotated[str, Field(alias='parentSpecificationId')]
    """
    Unique identifier of the parent specification containing the target characteristic
    """


class CharacteristicValueSpecification(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic value can take on, such as numeric, text and so forth
    """
    is_default: Annotated[bool | None, Field(alias='isDefault')] = None
    """
    If true, the Boolean Indicates if the value is the default value for a characteristic
    """
    unit_of_measure: Annotated[str | None, Field(alias='unitOfMeasure')] = None
    """
    A length, surface, volume, dry measure, liquid measure, money, weight, time, and the like. In general, a determinate quantity or magnitude of the kind designated, taken as a standard of comparison for others of the same kind, in assigning to them numerical values, as 1 foot, 1 yard, 1 mile, 1 square foot.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    value_from: Annotated[int | None, Field(alias='valueFrom')] = None
    """
    The low range value that a characteristic can take on
    """
    value_to: Annotated[int | None, Field(alias='valueTo')] = None
    """
    The upper range value that a characteristic can take on
    """
    range_interval: Annotated[str | None, Field(alias='rangeInterval')] = None
    """
    An indicator that specifies the inclusion or exclusion of the valueFrom and valueTo attributes. If applicable, possible values are "open", "closed", "closedBottom" and "closedTop".
    """
    regex: str | None = None
    """
    A regular expression constraint for given value
    """


class Entity(Extensible, Addressable):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Attachment(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    The name of the attachment
    """
    description: Annotated[
        str | None, Field(examples=['Photograph of the Product'])
    ] = None
    """
    A narrative text describing the content of the attachment
    """
    url: Annotated[
        str | None,
        Field(examples=['http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f']),
    ] = None
    """
    Uniform Resource Locator, is a web page address (a subset of URI)
    """
    content: str | None = None
    """
    The actual contents of the attachment object, if embedded, encoded as base64
    """
    size: Quantity | None = None
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    attachment_type: Annotated[str | None, Field(alias='attachmentType')] = None
    """
    a business characterization of the purpose of the attachment, for example logo, instructionManual, contractCopy
    """
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    a technical characterization of the attachment content format using IETF Mime Types
    """


class AttachmentFVO(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    The name of the attachment
    """
    description: Annotated[
        str | None, Field(examples=['Photograph of the Product'])
    ] = None
    """
    A narrative text describing the content of the attachment
    """
    url: Annotated[
        str | None,
        Field(examples=['http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f']),
    ] = None
    """
    Uniform Resource Locator, is a web page address (a subset of URI)
    """
    content: str | None = None
    """
    The actual contents of the attachment object, if embedded, encoded as base64
    """
    size: Quantity | None = None
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    attachment_type: Annotated[str, Field(alias='attachmentType')]
    """
    a business characterization of the purpose of the attachment, for example logo, instructionManual, contractCopy
    """
    mime_type: Annotated[str, Field(alias='mimeType')]
    """
    a technical characterization of the attachment content format using IETF Mime Types
    """


class AttachmentMVO(Attachment):
    pass


class BaseEvent(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: dict[str, Any] | None = None
    event_id: Annotated[str | None, Field(alias='eventId')] = None
    """
    The identifier of the notification.
    """
    event_time: Annotated[AwareDatetime | None, Field(alias='eventTime')] = None
    """
    Time of the event occurrence.
    """
    event_type: Annotated[str | None, Field(alias='eventType')] = None
    """
    The type of the notification.
    """
    correlation_id: Annotated[str | None, Field(alias='correlationId')] = None
    """
    The correlation id for this event.
    """
    domain: str | None = None
    """
    The domain of the event.
    """
    title: str | None = None
    """
    The title of the event.
    """
    description: str | None = None
    """
    An explanatory of the event.
    """
    priority: str | None = None
    """
    A priority.
    """
    time_ocurred: Annotated[AwareDatetime | None, Field(alias='timeOcurred')] = None
    """
    The time the event occured.
    """


class EntityMVO(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class EntityRefMVO(Extensible, Addressable):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    Name of the referred entity.
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
    """
    The actual type of the target instance when needed for disambiguation.
    """


class AttachmentRefMVO(EntityRefMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A narrative text describing the content of the attachment
    """
    url: str | None = None
    """
    Link to the attachment media/content
    """


class ConstraintRefMVO(EntityRefMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    version: str | None = None
    """
    constraint version
    """


class EntitySpecification(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    Name given to the specification
    """
    description: str | None = None
    """
    Description of the specification
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of the specification
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this catalog item
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether specification represents a single specification (false), or a bundle of specifications (true).
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    version: str | None = None
    """
    specification version
    """
    attachment: (
        list[Annotated[Attachment | AttachmentRef, Field(discriminator='field_type')]]
        | None
    ) = None
    """
    Attachments that may be of relevance to this specification, such as picture, document, media
    """
    target_entity_schema: Annotated[
        TargetEntitySchema | None, Field(alias='targetEntitySchema')
    ] = None
    spec_characteristic: Annotated[
        list[CharacteristicSpecification] | None, Field(alias='specCharacteristic')
    ] = None
    """
    List of characteristics that the entity can take
    """
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRef] | None, Field(alias='relatedParty')
    ] = None
    """
    Parties who manage or otherwise have an interest in this specification
    """
    constraint: list[ConstraintRef] | None = None
    """
    This is a list of constraint references applied to this specification
    """
    entity_spec_relationship: Annotated[
        list[EntitySpecificationRelationship] | None,
        Field(alias='entitySpecRelationship'),
    ] = None
    """
    Relationship to another specification
    """


class EntitySpecificationFVO(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    Name given to the specification
    """
    description: str | None = None
    """
    Description of the specification
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of the specification
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this catalog item
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether specification represents a single specification (false), or a bundle of specifications (true).
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    version: str | None = None
    """
    specification version
    """
    attachment: (
        list[
            Annotated[
                AttachmentFVO | AttachmentRefFVO, Field(discriminator='field_type')
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this specification, such as picture, document, media
    """
    target_entity_schema: Annotated[
        TargetEntitySchemaFVO | None, Field(alias='targetEntitySchema')
    ] = None
    spec_characteristic: Annotated[
        list[CharacteristicSpecificationFVO] | None, Field(alias='specCharacteristic')
    ] = None
    """
    List of characteristics that the entity can take
    """
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRefFVO] | None, Field(alias='relatedParty')
    ] = None
    """
    Parties who manage or otherwise have an interest in this specification
    """
    constraint: list[ConstraintRefFVO] | None = None
    """
    This is a list of constraint references applied to this specification
    """
    entity_spec_relationship: Annotated[
        list[EntitySpecificationRelationshipFVO] | None,
        Field(alias='entitySpecRelationship'),
    ] = None
    """
    Relationship to another specification
    """


class EntitySpecificationMVO(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    Name given to the specification
    """
    description: str | None = None
    """
    Description of the specification
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this catalog item
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether specification represents a single specification (false), or a bundle of specifications (true).
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    version: str | None = None
    """
    specification version
    """
    attachment: (
        list[Annotated[Attachment | AttachmentRef, Field(discriminator='field_type')]]
        | None
    ) = None
    """
    Attachments that may be of relevance to this specification, such as picture, document, media
    """
    target_entity_schema: Annotated[
        TargetEntitySchemaMVO | None, Field(alias='targetEntitySchema')
    ] = None
    spec_characteristic: Annotated[
        list[CharacteristicSpecificationMVO] | None, Field(alias='specCharacteristic')
    ] = None
    """
    List of characteristics that the entity can take
    """
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRefMVO] | None, Field(alias='relatedParty')
    ] = None
    """
    Parties who manage or otherwise have an interest in this specification
    """
    constraint: list[ConstraintRefMVO] | None = None
    """
    This is a list of constraint references applied to this specification
    """
    entity_spec_relationship: Annotated[
        list[EntitySpecificationRelationshipMVO] | None,
        Field(alias='entitySpecRelationship'),
    ] = None
    """
    Relationship to another specification
    """


class Error(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    """
    Application relevant detail, defined in the API or a common list.
    """
    reason: str
    """
    Explanation of the reason for the error which can be shown to a client user.
    """
    message: str | None = None
    """
    More details and corrective actions related to the error which can be shown to a client user.
    """
    status: str | None = None
    """
    HTTP Error code extension
    """
    reference_error: Annotated[str | None, Field(alias='referenceError')] = None
    """
    URI of documentation describing the error.
    """


class Event(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    href: str | None = None
    """
    Hyperlink reference
    """
    id: str | None = None
    """
    unique identifier
    """
    correlation_id: Annotated[str | None, Field(alias='correlationId')] = None
    """
    The correlation id for this event.
    """
    domain: str | None = None
    """
    The domain of the event.
    """
    title: str | None = None
    """
    The title of the event.
    """
    description: str | None = None
    """
    An explnatory of the event.
    """
    priority: str | None = None
    """
    A priority.
    """
    time_occurred: Annotated[AwareDatetime | None, Field(alias='timeOccurred')] = None
    """
    The time the event occurred.
    """
    source: EntityRef | None = None
    reporting_system: Annotated[EntityRef | None, Field(alias='reportingSystem')] = None
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRef] | None, Field(alias='relatedParty')
    ] = None
    analytic_characteristic: Annotated[
        list[
            BooleanArrayCharacteristic
            | BooleanCharacteristic
            | IntegerArrayCharacteristic
            | IntegerCharacteristic
            | NumberArrayCharacteristic
            | NumberCharacteristic
            | ObjectArrayCharacteristic
            | ObjectCharacteristic
            | StringArrayCharacteristic
            | StringCharacteristic
        ]
        | None,
        Field(alias='analyticCharacteristic'),
    ] = None
    event_id: Annotated[str | None, Field(alias='eventId')] = None
    """
    The identifier of the notification.
    """
    event_time: Annotated[AwareDatetime | None, Field(alias='eventTime')] = None
    """
    Time of the event occurrence.
    """
    event_type: Annotated[str | None, Field(alias='eventType')] = None
    """
    The type of the notification.
    """
    event: dict[str, Any] | None = None
    """
    The event linked to the involved resource object
    """


class ExpressionSpecification(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_language: Annotated[str | None, Field(alias='expressionLanguage')] = None
    """
    The serialized Expression language of the target intent.
    """
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """
    field_type: Literal['ExpressionSpecification'] = Field(..., alias='@type')


class ExtensibleFVO(Extensible):
    pass


class CharacteristicFVO(ExtensibleFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    name: str
    """
    Name of the characteristic
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    Data type of the value of the characteristic
    """
    characteristic_relationship: Annotated[
        list[CharacteristicRelationshipFVO] | None,
        Field(alias='characteristicRelationship'),
    ] = None


class BooleanArrayCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[bool]


class BooleanCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: bool
    """
    Value of the characteristic
    """


class CharacteristicRelationshipFVO(ExtensibleFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique identifier of the characteristic
    """
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    The type of relationship
    """


class ExtensibleMVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """


class CharacteristicMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    Name of the characteristic
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    Data type of the value of the characteristic
    """
    characteristic_relationship: Annotated[
        list[CharacteristicRelationshipMVO] | None,
        Field(alias='characteristicRelationship'),
    ] = None


class BooleanArrayCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[bool] | None = None


class BooleanCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: bool | None = None
    """
    Value of the characteristic
    """


class CharacteristicRelationshipMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    The type of relationship
    """


class CharacteristicSpecificationMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = None
    """
    A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic can take on, such as numeric, text and so forth
    """
    description: str | None = None
    """
    A narrative that explains the CharacteristicSpecification.
    """
    configurable: bool | None = None
    """
    If true, the Boolean indicates that the target Characteristic is configurable
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    min_cardinality: Annotated[int | None, Field(alias='minCardinality')] = None
    """
    The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.
    """
    max_cardinality: Annotated[int | None, Field(alias='maxCardinality')] = None
    """
    The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.
    """
    is_unique: Annotated[bool | None, Field(alias='isUnique')] = None
    """
    Specifies if the value of this characteristic is unique across all entities instantiated from the specification that uses this characteristc. For example, consider a ProductSpecification for a set-top box, with a CharacteristicSpecification cardID. Each set-top box must have a different value for cardID, so this isUnique attribute would be set to true for the characteristic.
    """
    regex: str | None = None
    """
    A rule or principle represented in regular expression used to derive the value of a characteristic value.
    """
    extensible: bool | None = None
    """
    An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.
    """
    field_value_schema_location: Annotated[
        str | None, Field(alias='@valueSchemaLocation')
    ] = None
    """
    This (optional) field provides a link to the schema describing the value type.
    """
    char_spec_relationship: Annotated[
        list[CharacteristicSpecificationRelationshipMVO] | None,
        Field(alias='charSpecRelationship'),
    ] = None
    """
    An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.
    """
    characteristic_value_specification: Annotated[
        list[CharacteristicValueSpecificationMVO] | None,
        Field(alias='characteristicValueSpecification'),
    ] = None
    """
    A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a CharacteristicSpecification object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding Characteristic object can take on.
    """


class CharacteristicSpecificationRelationshipMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as aggregation, migration, substitution, dependency, exclusivity
    """
    name: str
    """
    Name of the target characteristic within the specification
    """
    characteristic_specification_id: Annotated[
        str | None, Field(alias='characteristicSpecificationId')
    ] = None
    """
    Unique identifier of the characteristic within the specification
    """
    parent_specification_href: Annotated[
        AnyUrl | None, Field(alias='parentSpecificationHref')
    ] = None
    """
    Hyperlink reference to the parent specification containing the target characteristic
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    parent_specification_id: Annotated[str, Field(alias='parentSpecificationId')]
    """
    Unique identifier of the parent specification containing the target characteristic
    """


class CharacteristicValueSpecificationMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic value can take on, such as numeric, text and so forth
    """
    is_default: Annotated[bool | None, Field(alias='isDefault')] = None
    """
    If true, the Boolean Indicates if the value is the default value for a characteristic
    """
    unit_of_measure: Annotated[str | None, Field(alias='unitOfMeasure')] = None
    """
    A length, surface, volume, dry measure, liquid measure, money, weight, time, and the like. In general, a determinate quantity or magnitude of the kind designated, taken as a standard of comparison for others of the same kind, in assigning to them numerical values, as 1 foot, 1 yard, 1 mile, 1 square foot.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    value_from: Annotated[int | None, Field(alias='valueFrom')] = None
    """
    The low range value that a characteristic can take on
    """
    value_to: Annotated[int | None, Field(alias='valueTo')] = None
    """
    The upper range value that a characteristic can take on
    """
    range_interval: Annotated[str | None, Field(alias='rangeInterval')] = None
    """
    An indicator that specifies the inclusion or exclusion of the valueFrom and valueTo attributes. If applicable, possible values are "open", "closed", "closedBottom" and "closedTop".
    """
    regex: str | None = None
    """
    A regular expression constraint for given value
    """


class ExpressionSpecificationMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_language: Annotated[str | None, Field(alias='expressionLanguage')] = None
    """
    The serialized Expression language of the target intent.
    """
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """
    field_type: Literal['ExpressionSpecification'] = Field(..., alias='@type')


class FieldContainer(StrEnum):
    FIELD_LANGUAGE = '@language'
    FIELD_LIST = '@list'
    FIELD_INDEX = '@index'
    FIELD_SET = '@set'


class Graph(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_graph: Annotated[
        list[JsonLdExpressionValue] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class GraphFVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_graph: Annotated[
        list[JsonLdExpressionValueFVO] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class GraphMVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    field_graph: Annotated[
        list[JsonLdExpressionValueMVO] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class Hub(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    """
    Id of the listener
    """
    callback: str
    """
    The callback being registered.
    """
    query: str | None = None
    """
    additional data to be passed
    """


class HubFVO(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    callback: str
    """
    The callback being registered.
    """
    query: str | None = None
    """
    additional data to be passed
    """


class IntegerArrayCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[int] | None = None


class IntegerArrayCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[int]


class IntegerArrayCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[int] | None = None


class IntegerCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: int | None = None
    """
    Value of the characteristic
    """


class IntegerCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: int
    """
    Value of the characteristic
    """


class IntegerCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: int | None = None
    """
    Value of the characteristic
    """


class Intent(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    status_change_date: Annotated[
        AwareDatetime | None, Field(alias='statusChangeDate')
    ] = None
    """
    A date time( DateTime). The date that the entity status changed to the current one
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    version: str | None = None
    """
    A field that identifies the specific version of an instance of an intent.
    """
    intent_specification: Annotated[
        EntityRef | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[EntityRelationship] | None, Field(alias='intentRelationship')
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            BooleanArrayCharacteristic
            | BooleanCharacteristic
            | IntegerArrayCharacteristic
            | IntegerCharacteristic
            | NumberArrayCharacteristic
            | NumberCharacteristic
            | ObjectArrayCharacteristic
            | ObjectCharacteristic
            | StringArrayCharacteristic
            | StringCharacteristic
        ]
        | None
    ) = None
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRef] | None, Field(alias='relatedParty')
    ] = None
    attachment: (
        list[Annotated[Attachment | AttachmentRef, Field(discriminator='field_type')]]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str | None = None
    """
    The name of the intent.
    """
    expression: Annotated[
        JsonLdExpression | TurtleExpression | None, Field(discriminator='field_type')
    ] = None
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this REST resource
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of this REST resource
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """


class IntentAttributeValueChangeEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentAttributeValueChangeEventPayload | None = None


class IntentAttributeValueChangeEventPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    intent: Annotated[ProbeIntent | None, Field(discriminator='field_type')] = None


class IntentCreateEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentCreateEventPayload | None = None


class IntentCreateEventPayload(IntentAttributeValueChangeEventPayload):
    pass


class IntentDeleteEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentDeleteEventPayload | None = None


class IntentDeleteEventPayload(IntentAttributeValueChangeEventPayload):
    pass


class IntentExpression(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """


class IntentExpressionFVO(ExtensibleFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    iri: str
    """
    Internationalized Resource Identifier of the intent Expression
    """


class IntentExpressionMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """


class IntentFVO(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    status_change_date: Annotated[
        AwareDatetime | None, Field(alias='statusChangeDate')
    ] = None
    """
    A date time( DateTime). The date that the entity status changed to the current one
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    version: str | None = None
    """
    A field that identifies the specific version of an instance of an intent.
    """
    intent_specification: Annotated[
        EntityRefFVO | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[EntityRelationshipFVO] | None, Field(alias='intentRelationship')
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            BooleanArrayCharacteristicFVO
            | BooleanCharacteristicFVO
            | IntegerArrayCharacteristicFVO
            | IntegerCharacteristicFVO
            | NumberArrayCharacteristicFVO
            | NumberCharacteristicFVO
            | ObjectArrayCharacteristicFVO
            | ObjectCharacteristicFVO
            | StringArrayCharacteristicFVO
            | StringCharacteristicFVO
        ]
        | None
    ) = None
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRefFVO] | None, Field(alias='relatedParty')
    ] = None
    attachment: (
        list[
            Annotated[
                AttachmentFVO | AttachmentRefFVO, Field(discriminator='field_type')
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str
    """
    The name of the intent.
    """
    expression: Annotated[
        JsonLdExpressionFVO | TurtleExpressionFVO, Field(discriminator='field_type')
    ]
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this REST resource
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of this REST resource
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """


class IntentMVO(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    intent_specification: Annotated[
        EntityRefMVO | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[EntityRelationshipMVO] | None, Field(alias='intentRelationship')
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            BooleanArrayCharacteristicMVO
            | BooleanCharacteristicMVO
            | IntegerArrayCharacteristicMVO
            | IntegerCharacteristicMVO
            | NumberArrayCharacteristicMVO
            | NumberCharacteristicMVO
            | ObjectArrayCharacteristicMVO
            | ObjectCharacteristicMVO
            | StringArrayCharacteristicMVO
            | StringCharacteristicMVO
        ]
        | None
    ) = None
    related_party: Annotated[
        list[RelatedPartyRefOrPartyRoleRefMVO] | None, Field(alias='relatedParty')
    ] = None
    attachment: (
        list[
            Annotated[
                AttachmentMVO | AttachmentRefMVO, Field(discriminator='field_type')
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str | None = None
    """
    The name of the intent.
    """
    expression: Annotated[
        JsonLdExpressionMVO | TurtleExpressionMVO | None,
        Field(discriminator='field_type'),
    ] = None
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """


class IntentRef(EntityRef):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class AssociationSpecificationRef(IntentRef):
    field_type: Literal['reuse'] = Field(..., alias='@type')


class IntentReport(Entity):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    The description of the intent report.
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None
    intent: Annotated[
        IntentRef | ProbeIntent | None, Field(discriminator='field_type')
    ] = None
    """
    Intent Ref (if Intent already exists) or Value (if Intent be created or its details be presented)
    """
    name: str | None = None
    """
    The name of the intent report.
    """
    expression: Annotated[
        JsonLdExpression | TurtleExpression | None, Field(discriminator='field_type')
    ] = None
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this intent report
    """
    field_type: Literal['IntentReport'] = Field(..., alias='@type')


class IntentReportAttributeValueChange(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentReportAttributeValueChangePayload | None = None


class IntentReportAttributeValueChangePayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    intent_report: Annotated[
        IntentReport | None, Field(alias='intentReport', discriminator='field_type')
    ] = None


class IntentReportCreateEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentReportCreateEventPayload | None = None


class IntentReportCreateEventPayload(IntentReportAttributeValueChangePayload):
    pass


class IntentReportDeleteEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentReportDeleteEventPayload | None = None


class IntentReportDeleteEventPayload(IntentReportAttributeValueChangePayload):
    pass


class IntentSpecification(EntitySpecification):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_specification: Annotated[
        ExpressionSpecification | None,
        Field(alias='expressionSpecification', discriminator='field_type'),
    ] = None
    intent_spec_relationship: Annotated[
        list[IntentSpecificationRelationship] | None,
        Field(alias='intentSpecRelationship'),
    ] = None
    """
    A list of intent specifications related to this specification, e.g. substitution, dependency or exclusivity relationship
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent specification represents a single intent specification (false), or a bundle of intent specifications(true).
    """
    version: str | None = None
    """
    A field that identifies the specific version of this specification. If not specified version is defaulted to 1.0
    """


class IntentSpecificationAttributeValueChangeEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentSpecificationAttributeValueChangeEventPayload | None = None


class IntentSpecificationAttributeValueChangeEventPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    intent_specification: Annotated[
        IntentSpecification | None, Field(alias='intentSpecification')
    ] = None


class IntentSpecificationCreateEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentSpecificationCreateEventPayload | None = None


class IntentSpecificationCreateEventPayload(
    IntentSpecificationAttributeValueChangeEventPayload
):
    pass


class IntentSpecificationDeleteEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentSpecificationDeleteEventPayload | None = None


class IntentSpecificationDeleteEventPayload(
    IntentSpecificationAttributeValueChangeEventPayload
):
    pass


class IntentSpecificationFVO(EntitySpecificationFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_specification: Annotated[
        ExpressionSpecification | None,
        Field(alias='expressionSpecification', discriminator='field_type'),
    ] = None
    intent_spec_relationship: Annotated[
        list[IntentSpecificationRelationshipFVO] | None,
        Field(alias='intentSpecRelationship'),
    ] = None
    """
    A list of intent specifications related to this specification, e.g. substitution, dependency or exclusivity relationship
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent specification represents a single intent specification (false), or a bundle of intent specifications(true).
    """
    version: str | None = None
    """
    A field that identifies the specific version of this specification. If not specified version is defaulted to 1.0
    """


class IntentSpecificationMVO(EntitySpecificationMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_specification: Annotated[
        ExpressionSpecificationMVO | None,
        Field(alias='expressionSpecification', discriminator='field_type'),
    ] = None
    intent_spec_relationship: Annotated[
        list[IntentSpecificationRelationshipMVO] | None,
        Field(alias='intentSpecRelationship'),
    ] = None
    """
    A list of intent specifications related to this specification, e.g. substitution, dependency or exclusivity relationship
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent specification represents a single intent specification (false), or a bundle of intent specifications(true).
    """
    version: str | None = None
    """
    A field that identifies the specific version of this specification. If not specified version is defaulted to 1.0
    """


class IntentSpecificationRelationship(EntityRef):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = None
    """
    The association role for this intent specification
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as substitution, dependency, exclusivity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None


class IntentSpecificationRelationshipFVO(EntityRefFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = None
    """
    The association role for this intent specification
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as substitution, dependency, exclusivity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None


class IntentSpecificationRelationshipMVO(EntityRefMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = None
    """
    The association role for this intent specification
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as substitution, dependency, exclusivity
    """
    valid_for: Annotated[TimePeriod | None, Field(alias='validFor')] = None


class IntentSpecificationStatusChangeEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentSpecificationStatusChangeEventPayload | None = None


class IntentSpecificationStatusChangeEventPayload(
    IntentSpecificationAttributeValueChangeEventPayload
):
    pass


class IntentStatusChangeEvent(Event):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: IntentStatusChangeEventPayload | None = None


class IntentStatusChangeEventPayload(IntentAttributeValueChangeEventPayload):
    pass


class JsonLdExpression(IntentExpression):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[
        JsonLdExpressionValue | None, Field(alias='expressionValue')
    ] = None
    field_type: Literal['JsonLdExpression'] = Field(..., alias='@type')


class JsonLdExpressionFVO(IntentExpressionFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[
        JsonLdExpressionValueFVO, Field(alias='expressionValue')
    ]
    field_type: Literal['JsonLdExpression'] = Field(..., alias='@type')


class JsonLdExpressionMVO(IntentExpressionMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[
        JsonLdExpressionValueMVO, Field(alias='expressionValue')
    ]
    field_type: Literal['JsonLdExpression'] = Field(..., alias='@type')


class JsonLdExpressionValue(Context, Graph, Common):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )


class JsonLdExpressionValueFVO(ContextFVO, GraphFVO, CommonFVO):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )


class JsonLdExpressionValueMVO(ContextMVO, GraphMVO, CommonMVO):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )


class JsonPatch(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    op: Op
    """
    The operation to be performed
    """
    path: str
    """
    A JSON-Pointer
    """
    value: Any | None = None
    """
    The value to be used within the operations.
    """
    from_: Annotated[str | None, Field(alias='from')] = None
    """
    A string containing a JSON Pointer value.
    """


class JsonPatchOperations(RootModel[list[JsonPatch]]):
    root: list[JsonPatch]
    """
    JSONPatch Operations document as defined by RFC 6902
    """


class NumberArrayCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[float] | None = None


class NumberArrayCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[float]


class NumberArrayCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[float] | None = None


class NumberCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float | None = None
    """
    Value of the characteristic
    """


class NumberCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    """
    Value of the characteristic
    """


class NumberCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float | None = None
    """
    Value of the characteristic
    """


class ObjectArrayCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[dict[str, Any]] | None = None


class ObjectArrayCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[dict[str, Any]]


class ObjectArrayCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[dict[str, Any]] | None = None


class ObjectCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: dict[str, Any] | None = None
    """
    Value of the characteristic
    """


class ObjectCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: dict[str, Any]
    """
    Value of the characteristic
    """


class ObjectCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: dict[str, Any] | None = None
    """
    Value of the characteristic
    """


class Op(StrEnum):
    ADD = 'add'
    REMOVE = 'remove'
    REPLACE = 'replace'
    MOVE = 'move'
    COPY = 'copy'
    TEST = 'test'


class PartyRef(IntentRef):
    pass


class PartyRefFVO(EntityRefFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class AssociationSpecificationRefFVO(PartyRefFVO):
    field_type: Literal['reuse'] = Field(..., alias='@type')


class PartyRefMVO(EntityRefMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class AssociationSpecificationRefMVO(PartyRefMVO):
    field_type: Literal['reuse'] = Field(..., alias='@type')


class PartyRoleRef(EntityRef):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    party_id: Annotated[str | None, Field(alias='partyId')] = None
    """
    The identifier of the engaged party that is linked to the PartyRole object.
    """
    party_name: Annotated[str | None, Field(alias='partyName')] = None
    """
    The name of the engaged party that is linked to the PartyRole object.
    """


class PartyRoleRefFVO(EntityRefFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    party_id: Annotated[str | None, Field(alias='partyId')] = None
    """
    The identifier of the engaged party that is linked to the PartyRole object.
    """
    party_name: Annotated[str | None, Field(alias='partyName')] = None
    """
    The name of the engaged party that is linked to the PartyRole object.
    """


class PartyRoleRefMVO(EntityRefMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    party_id: Annotated[str | None, Field(alias='partyId')] = None
    """
    The identifier of the engaged party that is linked to the PartyRole object.
    """
    party_name: Annotated[str | None, Field(alias='partyName')] = None
    """
    The name of the engaged party that is linked to the PartyRole object.
    """


class ProbeIntent(Intent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Literal['ProbeIntent'] = Field(..., alias='@type')


class ProbeIntentFVO(IntentFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class ProbeIntentMVO(IntentMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Quantity(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    amount: float = 1
    """
    Numeric value in a given unit
    """
    units: str | None = None
    """
    Unit
    """


class RelatedPartyRefOrPartyRoleRef(Extensible):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = None
    """
    Role played by the related party or party role in the context of the specific entity it is linked to. Such as 'initiator', 'customer',  'salesAgent', 'user'
    """
    party_or_party_role: Annotated[
        PartyRef | PartyRoleRef | None,
        Field(alias='partyOrPartyRole', discriminator='field_type'),
    ] = None


class RelatedPartyRefOrPartyRoleRefFVO(ExtensibleFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str
    """
    Role played by the related party or party role in the context of the specific entity it is linked to. Such as 'initiator', 'customer',  'salesAgent', 'user'
    """
    party_or_party_role: Annotated[
        PartyRefFVO | PartyRoleRefFVO | None,
        Field(alias='partyOrPartyRole', discriminator='field_type'),
    ] = None


class RelatedPartyRefOrPartyRoleRefMVO(ExtensibleMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = None
    """
    Role played by the related party or party role in the context of the specific entity it is linked to. Such as 'initiator', 'customer',  'salesAgent', 'user'
    """
    party_or_party_role: Annotated[
        PartyRefMVO | PartyRoleRefMVO | None,
        Field(alias='partyOrPartyRole', discriminator='field_type'),
    ] = None


class StringArrayCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[str] | None = None


class StringArrayCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[str]


class StringArrayCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: list[str] | None = None


class StringCharacteristic(Characteristic):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str | None = None
    """
    Value of the characteristic
    """


class StringCharacteristicFVO(CharacteristicFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    """
    Value of the characteristic
    """


class StringCharacteristicMVO(CharacteristicMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str | None = None
    """
    Value of the characteristic
    """


class TargetEntitySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Annotated[str | None, Field(alias='@type')] = None
    """
    Class type of the target entity
    """
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    This field provides a link to the schema describing the target entity
    """


class TargetEntitySchemaFVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_type: Annotated[str, Field(alias='@type')]
    """
    Class type of the target entity
    """
    field_schema_location: Annotated[str, Field(alias='@schemaLocation')]
    """
    This field provides a link to the schema describing the target entity
    """


class TargetEntitySchemaMVO(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    This field provides a link to the schema describing the target entity
    """


class TimePeriod(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_date_time: Annotated[
        AwareDatetime | None,
        Field(alias='startDateTime', examples=['1985-04-12T23:20:50.52Z']),
    ] = None
    """
    Start of the time period, using IETC-RFC-3339 format
    """
    end_date_time: Annotated[
        AwareDatetime | None,
        Field(alias='endDateTime', examples=['1985-04-12T23:20:50.52Z']),
    ] = None
    """
    End of the time period, using IETC-RFC-3339 format
    """


class TurtleExpression(IntentExpression):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[str | None, Field(alias='expressionValue')] = None
    """
    Turtle Expression value is the ontology-encoded form of the Intent as Turtle RDF as defined in https://www.w3.org/TR/turtle/
    """
    field_type: Literal['TurtleExpression'] = Field(..., alias='@type')


class TurtleExpressionFVO(IntentExpressionFVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[str, Field(alias='expressionValue')]
    """
    Turtle Expression value is the ontology-encoded form of the Intent as Turtle RDF as defined in https://www.w3.org/TR/turtle/
    """
    field_type: Literal['TurtleExpression'] = Field(..., alias='@type')


class TurtleExpressionMVO(IntentExpressionMVO):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    expression_value: Annotated[str, Field(alias='expressionValue')]
    """
    Turtle Expression value is the ontology-encoded form of the Intent as Turtle RDF as defined in https://www.w3.org/TR/turtle/
    """
    field_type: Literal['TurtleExpression'] = Field(..., alias='@type')


Graph.model_rebuild()
GraphFVO.model_rebuild()
GraphMVO.model_rebuild()
Intent.model_rebuild()
IntentAttributeValueChangeEvent.model_rebuild()
IntentAttributeValueChangeEventPayload.model_rebuild()
IntentCreateEvent.model_rebuild()
IntentCreateEventPayload.model_rebuild()
IntentDeleteEvent.model_rebuild()
IntentDeleteEventPayload.model_rebuild()
IntentFVO.model_rebuild()
IntentMVO.model_rebuild()
IntentReport.model_rebuild()
IntentReportAttributeValueChange.model_rebuild()
IntentReportCreateEvent.model_rebuild()
IntentReportDeleteEvent.model_rebuild()
IntentStatusChangeEvent.model_rebuild()
IntentStatusChangeEventPayload.model_rebuild()
JsonLdExpression.model_rebuild()
JsonLdExpressionFVO.model_rebuild()
JsonLdExpressionMVO.model_rebuild()
JsonLdExpressionValue.model_rebuild()
JsonLdExpressionValueFVO.model_rebuild()
JsonLdExpressionValueMVO.model_rebuild()
ProbeIntent.model_rebuild()
ProbeIntentFVO.model_rebuild()
ProbeIntentMVO.model_rebuild()
