# generated by datamodel-codegen:
#   filename:  _internal_1

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from .common_fvo import CommonFVO
from .context_fvo import ContextFVO


class GraphFVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_graph: Annotated[
        list[JsonLdExpressionValueFVO] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class JsonLdExpressionValueFVO(ContextFVO, GraphFVO, CommonFVO):
    model_config = ConfigDict(
        extra='allow',
    )


GraphFVO.model_rebuild()
JsonLdExpressionValueFVO.model_rebuild()
