# generated by datamodel-codegen:
#   filename:  _internal_2

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from .common_mvo import CommonMVO
from .context_mvo import ContextMVO


class GraphMVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_graph: Annotated[
        list[JsonLdExpressionValueMVO] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class JsonLdExpressionValueMVO(ContextMVO, GraphMVO, CommonMVO):
    model_config = ConfigDict(
        extra='allow',
    )


GraphMVO.model_rebuild()
JsonLdExpressionValueMVO.model_rebuild()
