# generated by datamodel-codegen:
#   filename:  _internal

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from .common import Common
from .context import Context


class Graph(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_graph: Annotated[
        list[JsonLdExpressionValue] | None, Field(alias='@graph')
    ] = None
    """
    Used to express a graph.
    """


class JsonLdExpressionValue(Context, Graph, Common):
    model_config = ConfigDict(
        extra='allow',
    )


Graph.model_rebuild()
JsonLdExpressionValue.model_rebuild()
