# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from pydantic import BaseModel


class Addressable(BaseModel):
    href: str | None = None
    """
    Hyperlink reference
    """
    id: str | None = None
    """
    unique identifier
    """
