# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Literal

from pydantic import Field

from .entity_ref_fvo import EntityRefFVO


class AssociationSpecificationRefFVO(EntityRefFVO):
    field_type: Literal['AssociationSpecificationRef'] = Field(..., alias='@type')
