# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .entity_ref import EntityRef


class AttachmentRef(EntityRef):
    description: str | None = None
    """
    A narrative text describing the content of the attachment
    """
    url: str | None = None
    """
    Link to the attachment media/content
    """
