# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import attachment_mvo, attachment_ref_mvo


class AttachmentRefOrValueMVO(
    RootModel[attachment_mvo.AttachmentMVO | attachment_ref_mvo.AttachmentRefMVO]
):
    root: Annotated[
        attachment_mvo.AttachmentMVO | attachment_ref_mvo.AttachmentRefMVO,
        Field(discriminator='field_type'),
    ]
    """
    The polymorphic attributes @type, @schemaLocation & @referredType are related to the Attachment entity and not the AttachmentRefOrValue class itself
    """
