# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import attachment_fvo, attachment_ref_fvo


class AttachmentRefOrValueFVO(
    RootModel[attachment_fvo.AttachmentFVO | attachment_ref_fvo.AttachmentRefFVO]
):
    root: Annotated[
        attachment_fvo.AttachmentFVO | attachment_ref_fvo.AttachmentRefFVO,
        Field(discriminator='field_type'),
    ]
    """
    The polymorphic attributes @type, @schemaLocation & @referredType are related to the Attachment entity and not the AttachmentRefOrValue class itself
    """
