# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import quantity, time_period
from .entity import Entity


class AttachmentMVO(Entity):
    name: str | None = None
    """
    The name of the attachment
    """
    description: Annotated[
        str | None, Field(examples=['Photograph of the Product'])
    ] = None
    """
    A narrative text describing the content of the attachment
    """
    url: Annotated[
        str | None,
        Field(examples=['http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f']),
    ] = None
    """
    Uniform Resource Locator, is a web page address (a subset of URI)
    """
    content: str | None = None
    """
    The actual contents of the attachment object, if embedded, encoded as base64
    """
    size: quantity.Quantity | None = None
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    attachment_type: Annotated[str | None, Field(alias='attachmentType')] = None
    """
    a business characterization of the purpose of the attachment, for example logo, instructionManual, contractCopy
    """
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    a technical characterization of the attachment content format using IETF Mime Types
    """
