# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, Field

from .entity import Entity


class BaseEvent(Entity):
    event: dict[str, Any] | None = None
    event_id: Annotated[str | None, Field(alias='eventId')] = None
    """
    The identifier of the notification.
    """
    event_time: Annotated[AwareDatetime | None, Field(alias='eventTime')] = None
    """
    Time of the event occurrence.
    """
    event_type: Annotated[str | None, Field(alias='eventType')] = None
    """
    The type of the notification.
    """
    correlation_id: Annotated[str | None, Field(alias='correlationId')] = None
    """
    The correlation id for this event.
    """
    domain: str | None = None
    """
    The domain of the event.
    """
    title: str | None = None
    """
    The title of the event.
    """
    description: str | None = None
    """
    An explanatory of the event.
    """
    priority: str | None = None
    """
    A priority.
    """
    time_ocurred: Annotated[AwareDatetime | None, Field(alias='timeOcurred')] = None
    """
    The time the event occured.
    """
