# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .extensible_mvo import ExtensibleMVO


class CharacteristicRelationshipMVO(ExtensibleMVO):
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    The type of relationship
    """
