# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import time_period
from .extensible_mvo import ExtensibleMVO


class CharacteristicValueSpecificationMVO(ExtensibleMVO):
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic value can take on, such as numeric, text and so forth
    """
    is_default: Annotated[bool | None, Field(alias='isDefault')] = None
    """
    If true, the Boolean Indicates if the value is the default value for a characteristic
    """
    unit_of_measure: Annotated[str | None, Field(alias='unitOfMeasure')] = None
    """
    A length, surface, volume, dry measure, liquid measure, money, weight, time, and the like. In general, a determinate quantity or magnitude of the kind designated, taken as a standard of comparison for others of the same kind, in assigning to them numerical values, as 1 foot, 1 yard, 1 mile, 1 square foot.
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    value_from: Annotated[int | None, Field(alias='valueFrom')] = None
    """
    The low range value that a characteristic can take on
    """
    value_to: Annotated[int | None, Field(alias='valueTo')] = None
    """
    The upper range value that a characteristic can take on
    """
    range_interval: Annotated[str | None, Field(alias='rangeInterval')] = None
    """
    An indicator that specifies the inclusion or exclusion of the valueFrom and valueTo attributes. If applicable, possible values are "open", "closed", "closedBottom" and "closedTop".
    """
    regex: str | None = None
    """
    A regular expression constraint for given value
    """
