# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .extensible_fvo import ExtensibleFVO


class CharacteristicRelationshipFVO(ExtensibleFVO):
    id: str
    """
    Unique identifier of the characteristic
    """
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    The type of relationship
    """
