# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import characteristic_relationship_fvo
from .extensible_fvo import ExtensibleFVO


class CharacteristicFVO(ExtensibleFVO):
    id: str | None = None
    """
    Unique identifier of the characteristic
    """
    name: str
    """
    Name of the characteristic
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    Data type of the value of the characteristic
    """
    characteristic_relationship: Annotated[
        list[characteristic_relationship_fvo.CharacteristicRelationshipFVO] | None,
        Field(alias='characteristicRelationship'),
    ] = None
