# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import (
    characteristic_specification_relationship_mvo,
    characteristic_value_specification_mvo,
    time_period,
)
from .extensible_mvo import ExtensibleMVO


class CharacteristicSpecificationMVO(ExtensibleMVO):
    name: str | None = None
    """
    A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.
    """
    value_type: Annotated[str | None, Field(alias='valueType')] = None
    """
    A kind of value that the characteristic can take on, such as numeric, text and so forth
    """
    description: str | None = None
    """
    A narrative that explains the CharacteristicSpecification.
    """
    configurable: bool | None = None
    """
    If true, the Boolean indicates that the target Characteristic is configurable
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    min_cardinality: Annotated[int | None, Field(alias='minCardinality')] = None
    """
    The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.
    """
    max_cardinality: Annotated[int | None, Field(alias='maxCardinality')] = None
    """
    The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.
    """
    is_unique: Annotated[bool | None, Field(alias='isUnique')] = None
    """
    Specifies if the value of this characteristic is unique across all entities instantiated from the specification that uses this characteristc. For example, consider a ProductSpecification for a set-top box, with a CharacteristicSpecification cardID. Each set-top box must have a different value for cardID, so this isUnique attribute would be set to true for the characteristic.
    """
    regex: str | None = None
    """
    A rule or principle represented in regular expression used to derive the value of a characteristic value.
    """
    extensible: bool | None = None
    """
    An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.
    """
    field_value_schema_location: Annotated[
        str | None, Field(alias='@valueSchemaLocation')
    ] = None
    """
    This (optional) field provides a link to the schema describing the value type.
    """
    char_spec_relationship: Annotated[
        list[
            characteristic_specification_relationship_mvo.CharacteristicSpecificationRelationshipMVO
        ]
        | None,
        Field(alias='charSpecRelationship'),
    ] = None
    """
    An aggregation, migration, substitution, dependency or exclusivity relationship between/among Specification Characteristics.
    """
    characteristic_value_specification: Annotated[
        list[characteristic_value_specification_mvo.CharacteristicValueSpecificationMVO]
        | None,
        Field(alias='characteristicValueSpecification'),
    ] = None
    """
    A CharacteristicValueSpecification object is used to define a set of attributes, each of which can be assigned to a corresponding set of attributes in a CharacteristicSpecification object. The values of the attributes in the CharacteristicValueSpecification object describe the values of the attributes that a corresponding Characteristic object can take on.
    """
