# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AnyUrl, Field

from . import time_period
from .extensible import Extensible


class CharacteristicSpecificationRelationship(Extensible):
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as aggregation, migration, substitution, dependency, exclusivity
    """
    name: str | None = None
    """
    Name of the target characteristic within the specification
    """
    characteristic_specification_id: Annotated[
        str | None, Field(alias='characteristicSpecificationId')
    ] = None
    """
    Unique identifier of the characteristic within the specification
    """
    parent_specification_href: Annotated[
        AnyUrl | None, Field(alias='parentSpecificationHref')
    ] = None
    """
    Hyperlink reference to the parent specification containing the target characteristic
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    parent_specification_id: Annotated[
        str | None, Field(alias='parentSpecificationId')
    ] = None
    """
    Unique identifier of the parent specification containing the target characteristic
    """
