# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AnyUrl, Field

from . import time_period
from .extensible_mvo import ExtensibleMVO


class CharacteristicSpecificationRelationshipMVO(ExtensibleMVO):
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as aggregation, migration, substitution, dependency, exclusivity
    """
    name: str
    """
    Name of the target characteristic within the specification
    """
    characteristic_specification_id: Annotated[
        str | None, Field(alias='characteristicSpecificationId')
    ] = None
    """
    Unique identifier of the characteristic within the specification
    """
    parent_specification_href: Annotated[
        AnyUrl | None, Field(alias='parentSpecificationHref')
    ] = None
    """
    Hyperlink reference to the parent specification containing the target characteristic
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    parent_specification_id: Annotated[str, Field(alias='parentSpecificationId')]
    """
    Unique identifier of the parent specification containing the target characteristic
    """
