# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from . import field_container2


class CommonMVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_id: Annotated[AnyUrl | None, Field(alias='@id')] = None
    """
    Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.
    """
    field_value: Annotated[str | None, Field(alias='@value')] = None
    """
    Used to specify the data that is associated with a particular property in the graph.
    """
    field_language: Annotated[str | None, Field(alias='@language')] = None
    """
    Used to specify the language for a particular string value or the default language of a JSON-LD document.
    """
    field_container: Annotated[
        field_container2.FieldContainer | None, Field(alias='@container')
    ] = None
    """
    Used to set the default container type for a term.
    """
    field_list: Annotated[Any | None, Field(alias='@list')] = None
    """
    Used to express an ordered set of data.
    """
    field_set: Annotated[Any | None, Field(alias='@set')] = None
    """
    Used to express an unordered set of data and to ensure that values are always represented as arrays.
    """
    field_reverse: Annotated[str | None, Field(alias='@reverse')] = None
    """
    Used to express reverse properties.
    """
    field_base: Annotated[AnyUrl | None, Field(alias='@base')] = None
    """
    Used to set the base IRI against which relative IRIs are resolved
    """
    field_vocab: Annotated[AnyUrl | None, Field(alias='@vocab')] = None
    """
    Used to expand properties and values in @type with a common prefix IRI
    """
