# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .entity_ref import EntityRef


class ConstraintRef(EntityRef):
    version: str | None = None
    """
    constraint version
    """
