# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ContextMVO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_context: Annotated[dict[str, Any] | None, Field(alias='@context')] = None
    """
    Used to define the short-hand names that are used throughout a JSON-LD document.
    """
