# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .addressable import Addressable
from .extensible import Extensible


class EntityRefMVO(Extensible, Addressable):
    name: str | None = None
    """
    Name of the referred entity.
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
    """
    The actual type of the target instance when needed for disambiguation.
    """
