# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import association_specification_ref_mvo, time_period


class EntitySpecificationRelationshipMVO(BaseModel):
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity specification
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[
        association_specification_ref_mvo.AssociationSpecificationRefMVO | None,
        Field(alias='associationSpec', discriminator='field_type'),
    ] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
