# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import association_specification_ref_fvo, time_period


class EntitySpecificationRelationshipFVO(BaseModel):
    href: str | None = None
    name: str | None = None
    role: str
    """
    The association role for this entity specification
    """
    valid_for: Annotated[time_period.TimePeriod, Field(alias='validFor')]
    association_spec: Annotated[
        association_specification_ref_fvo.AssociationSpecificationRefFVO,
        Field(alias='associationSpec', discriminator='field_type'),
    ]
    field_base_type: Annotated[str | None, Field(alias='@baseType')] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    relationship_type: Annotated[str, Field(alias='relationshipType')]
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
