# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, Field

from . import (
    characteristic_specification_fvo,
    constraint_ref_fvo,
    entity_specification_relationship_fvo,
    related_party_ref_or_party_role_ref_fvo,
    target_entity_schema_fvo,
    time_period,
)
from .entity import Entity


class EntitySpecificationFVO(Entity):
    name: str
    """
    Name given to the specification
    """
    description: str | None = None
    """
    Description of the specification
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of the specification
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this catalog item
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether specification represents a single specification (false), or a bundle of specifications (true).
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    version: str | None = None
    """
    specification version
    """
    attachment: (
        list[
            Annotated[
                attachment_fvo.AttachmentFVO | attachment_ref_fvo.AttachmentRefFVO,
                Field(discriminator='field_type'),
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this specification, such as picture, document, media
    """
    target_entity_schema: Annotated[
        target_entity_schema_fvo.TargetEntitySchemaFVO | None,
        Field(alias='targetEntitySchema'),
    ] = None
    spec_characteristic: Annotated[
        list[characteristic_specification_fvo.CharacteristicSpecificationFVO] | None,
        Field(alias='specCharacteristic'),
    ] = None
    """
    List of characteristics that the entity can take
    """
    related_party: Annotated[
        list[related_party_ref_or_party_role_ref_fvo.RelatedPartyRefOrPartyRoleRefFVO]
        | None,
        Field(alias='relatedParty'),
    ] = None
    """
    Parties who manage or otherwise have an interest in this specification
    """
    constraint: list[constraint_ref_fvo.ConstraintRefFVO] | None = None
    """
    This is a list of constraint references applied to this specification
    """
    entity_spec_relationship: Annotated[
        list[entity_specification_relationship_fvo.EntitySpecificationRelationshipFVO]
        | None,
        Field(alias='entitySpecRelationship'),
    ] = None
    """
    Relationship to another specification
    """
