# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import entity_ref_mvo, time_period


class EntityRelationshipMVO(BaseModel):
    name: str | None = None
    role: str | None = None
    """
    The association role for this entity
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    association_spec: Annotated[
        entity_ref_mvo.EntityRefMVO | None, Field(alias='associationSpec')
    ] = None
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as migration, substitution, dependency, exclusivity
    """
    field_referred_type: Annotated[str | None, Field(alias='@referredType')] = None
