# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .extensible import Extensible


class Error(Extensible):
    code: str
    """
    Application relevant detail, defined in the API or a common list.
    """
    reason: str
    """
    Explanation of the reason for the error which can be shown to a client user.
    """
    message: str | None = None
    """
    More details and corrective actions related to the error which can be shown to a client user.
    """
    status: str | None = None
    """
    HTTP Error code extension
    """
    reference_error: Annotated[str | None, Field(alias='referenceError')] = None
    """
    URI of documentation describing the error.
    """
