# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, Field

from . import (
    boolean_array_characteristic,
    boolean_characteristic,
    entity_ref,
    integer_array_characteristic,
    integer_characteristic,
    number_array_characteristic,
    number_characteristic,
    object_array_characteristic,
    object_characteristic,
    related_party_ref_or_party_role_ref,
    string_array_characteristic,
    string_characteristic,
)
from .extensible import Extensible


class Event(Extensible):
    href: str | None = None
    """
    Hyperlink reference
    """
    id: str | None = None
    """
    unique identifier
    """
    correlation_id: Annotated[str | None, Field(alias='correlationId')] = None
    """
    The correlation id for this event.
    """
    domain: str | None = None
    """
    The domain of the event.
    """
    title: str | None = None
    """
    The title of the event.
    """
    description: str | None = None
    """
    An explnatory of the event.
    """
    priority: str | None = None
    """
    A priority.
    """
    time_occurred: Annotated[AwareDatetime | None, Field(alias='timeOccurred')] = None
    """
    The time the event occurred.
    """
    source: entity_ref.EntityRef | None = None
    reporting_system: Annotated[
        entity_ref.EntityRef | None, Field(alias='reportingSystem')
    ] = None
    related_party: Annotated[
        list[related_party_ref_or_party_role_ref.RelatedPartyRefOrPartyRoleRef] | None,
        Field(alias='relatedParty'),
    ] = None
    analytic_characteristic: Annotated[
        list[
            boolean_array_characteristic.BooleanArrayCharacteristic
            | boolean_characteristic.BooleanCharacteristic
            | integer_array_characteristic.IntegerArrayCharacteristic
            | integer_characteristic.IntegerCharacteristic
            | number_array_characteristic.NumberArrayCharacteristic
            | number_characteristic.NumberCharacteristic
            | object_array_characteristic.ObjectArrayCharacteristic
            | object_characteristic.ObjectCharacteristic
            | string_array_characteristic.StringArrayCharacteristic
            | string_characteristic.StringCharacteristic
        ]
        | None,
        Field(alias='analyticCharacteristic'),
    ] = None
    event_id: Annotated[str | None, Field(alias='eventId')] = None
    """
    The identifier of the notification.
    """
    event_time: Annotated[AwareDatetime | None, Field(alias='eventTime')] = None
    """
    Time of the event occurrence.
    """
    event_type: Annotated[str | None, Field(alias='eventType')] = None
    """
    The type of the notification.
    """
    event: dict[str, Any] | None = None
    """
    The event linked to the involved resource object
    """
