# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from .extensible_mvo import ExtensibleMVO


class ExpressionSpecificationMVO(ExtensibleMVO):
    expression_language: Annotated[str | None, Field(alias='expressionLanguage')] = None
    """
    The serialized Expression language of the target intent.
    """
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """
    field_type: Literal['ExpressionSpecification'] = Field(..., alias='@type')
