# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ExtensibleMVO(BaseModel):
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    A URI to a JSON-Schema file that defines additional attributes and relationships
    """
