# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from enum import StrEnum


class FieldContainer(StrEnum):
    FIELD_LANGUAGE = '@language'
    FIELD_LIST = '@list'
    FIELD_INDEX = '@index'
    FIELD_SET = '@set'
