# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .entity import Entity


class Hub(Entity):
    id: str | None = None
    """
    Id of the listener
    """
    callback: str
    """
    The callback being registered.
    """
    query: str | None = None
    """
    additional data to be passed
    """
