# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_create_event_payload
from .event import Event


class IntentCreateEvent(Event):
    event: intent_create_event_payload.IntentCreateEventPayload | None = None
