# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_report_attribute_value_change_payload
from .event import Event


class IntentReportAttributeValueChange(Event):
    event: (
        intent_report_attribute_value_change_payload.IntentReportAttributeValueChangePayload
        | None
    ) = None
