# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .extensible_fvo import ExtensibleFVO


class IntentExpressionFVO(ExtensibleFVO):
    iri: str
    """
    Internationalized Resource Identifier of the intent Expression
    """
