# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_delete_event_payload
from .event import Event


class IntentDeleteEvent(Event):
    event: intent_delete_event_payload.IntentDeleteEventPayload | None = None
