# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import intent_specification as intent_specification_1


class IntentSpecificationStatusChangeEventPayload(BaseModel):
    intent_specification: Annotated[
        intent_specification_1.IntentSpecification | None,
        Field(alias='intentSpecification'),
    ] = None
