# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import expression_specification as expression_specification_1
from . import intent_specification_relationship_fvo
from .entity_specification_fvo import EntitySpecificationFVO


class IntentSpecificationFVO(EntitySpecificationFVO):
    expression_specification: Annotated[
        expression_specification_1.ExpressionSpecification | None,
        Field(alias='expressionSpecification', discriminator='field_type'),
    ] = None
    intent_spec_relationship: Annotated[
        list[intent_specification_relationship_fvo.IntentSpecificationRelationshipFVO]
        | None,
        Field(alias='intentSpecRelationship'),
    ] = None
    """
    A list of intent specifications related to this specification, e.g. substitution, dependency or exclusivity relationship
    """
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent specification represents a single intent specification (false), or a bundle of intent specifications(true).
    """
    version: str | None = None
    """
    A field that identifies the specific version of this specification. If not specified version is defaulted to 1.0
    """
