# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_specification_status_change_event_payload
from .event import Event


class IntentSpecificationStatusChangeEvent(Event):
    event: (
        intent_specification_status_change_event_payload.IntentSpecificationStatusChangeEventPayload
        | None
    ) = None
