# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, Field

from . import (
    boolean_array_characteristic_fvo,
    boolean_characteristic_fvo,
    entity_ref_fvo,
    entity_relationship_fvo,
    integer_array_characteristic_fvo,
    integer_characteristic_fvo,
    json_ld_expression_fvo,
    number_array_characteristic_fvo,
    number_characteristic_fvo,
    object_array_characteristic_fvo,
    object_characteristic_fvo,
    related_party_ref_or_party_role_ref_fvo,
    string_array_characteristic_fvo,
    string_characteristic_fvo,
    time_period,
    turtle_expression_fvo,
)
from .entity import Entity


class IntentFVO(Entity):
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    status_change_date: Annotated[
        AwareDatetime | None, Field(alias='statusChangeDate')
    ] = None
    """
    A date time( DateTime). The date that the entity status changed to the current one
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    version: str | None = None
    """
    A field that identifies the specific version of an instance of an intent.
    """
    intent_specification: Annotated[
        entity_ref_fvo.EntityRefFVO | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[entity_relationship_fvo.EntityRelationshipFVO] | None,
        Field(alias='intentRelationship'),
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            boolean_array_characteristic_fvo.BooleanArrayCharacteristicFVO
            | boolean_characteristic_fvo.BooleanCharacteristicFVO
            | integer_array_characteristic_fvo.IntegerArrayCharacteristicFVO
            | integer_characteristic_fvo.IntegerCharacteristicFVO
            | number_array_characteristic_fvo.NumberArrayCharacteristicFVO
            | number_characteristic_fvo.NumberCharacteristicFVO
            | object_array_characteristic_fvo.ObjectArrayCharacteristicFVO
            | object_characteristic_fvo.ObjectCharacteristicFVO
            | string_array_characteristic_fvo.StringArrayCharacteristicFVO
            | string_characteristic_fvo.StringCharacteristicFVO
        ]
        | None
    ) = None
    related_party: Annotated[
        list[related_party_ref_or_party_role_ref_fvo.RelatedPartyRefOrPartyRoleRefFVO]
        | None,
        Field(alias='relatedParty'),
    ] = None
    attachment: (
        list[
            Annotated[
                attachment_fvo.AttachmentFVO | attachment_ref_fvo.AttachmentRefFVO,
                Field(discriminator='field_type'),
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str
    """
    The name of the intent.
    """
    expression: Annotated[
        json_ld_expression_fvo.JsonLdExpressionFVO
        | turtle_expression_fvo.TurtleExpressionFVO,
        Field(discriminator='field_type'),
    ]
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this REST resource
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of this REST resource
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """
