# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .extensible_mvo import ExtensibleMVO


class IntentExpressionMVO(ExtensibleMVO):
    iri: str | None = None
    """
    Internationalized Resource Identifier of the intent Expression
    """
