# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import time_period
from .entity_ref_fvo import EntityRefFVO


class IntentSpecificationRelationshipFVO(EntityRefFVO):
    role: str | None = None
    """
    The association role for this intent specification
    """
    relationship_type: Annotated[str | None, Field(alias='relationshipType')] = None
    """
    Type of relationship such as substitution, dependency, exclusivity
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
