# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_attribute_value_change_event_payload
from .event import Event


class IntentAttributeValueChangeEvent(Event):
    event: (
        intent_attribute_value_change_event_payload.IntentAttributeValueChangeEventPayload
        | None
    ) = None
