# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import intent_report as intent_report_1


class IntentReportCreateEventPayload(BaseModel):
    intent_report: Annotated[
        intent_report_1.IntentReport | None,
        Field(alias='intentReport', discriminator='field_type'),
    ] = None
