# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from . import (
    boolean_array_characteristic_mvo,
    boolean_characteristic_mvo,
    entity_ref_mvo,
    entity_relationship_mvo,
    integer_array_characteristic_mvo,
    integer_characteristic_mvo,
    json_ld_expression_mvo,
    number_array_characteristic_mvo,
    number_characteristic_mvo,
    object_array_characteristic_mvo,
    object_characteristic_mvo,
    related_party_ref_or_party_role_ref_mvo,
    string_array_characteristic_mvo,
    string_characteristic_mvo,
    time_period,
    turtle_expression_mvo,
)
from .entity import Entity


class IntentMVO(Entity):
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    intent_specification: Annotated[
        entity_ref_mvo.EntityRefMVO | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[entity_relationship_mvo.EntityRelationshipMVO] | None,
        Field(alias='intentRelationship'),
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            boolean_array_characteristic_mvo.BooleanArrayCharacteristicMVO
            | boolean_characteristic_mvo.BooleanCharacteristicMVO
            | integer_array_characteristic_mvo.IntegerArrayCharacteristicMVO
            | integer_characteristic_mvo.IntegerCharacteristicMVO
            | number_array_characteristic_mvo.NumberArrayCharacteristicMVO
            | number_characteristic_mvo.NumberCharacteristicMVO
            | object_array_characteristic_mvo.ObjectArrayCharacteristicMVO
            | object_characteristic_mvo.ObjectCharacteristicMVO
            | string_array_characteristic_mvo.StringArrayCharacteristicMVO
            | string_characteristic_mvo.StringCharacteristicMVO
        ]
        | None
    ) = None
    related_party: Annotated[
        list[related_party_ref_or_party_role_ref_mvo.RelatedPartyRefOrPartyRoleRefMVO]
        | None,
        Field(alias='relatedParty'),
    ] = None
    attachment: (
        list[
            Annotated[
                attachment_mvo.AttachmentMVO | attachment_ref_mvo.AttachmentRefMVO,
                Field(discriminator='field_type'),
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str | None = None
    """
    The name of the intent.
    """
    expression: Annotated[
        json_ld_expression_mvo.JsonLdExpressionMVO
        | turtle_expression_mvo.TurtleExpressionMVO
        | None,
        Field(discriminator='field_type'),
    ] = None
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """
