# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_specification_attribute_value_change_event_payload
from .event import Event


class IntentSpecificationAttributeValueChangeEvent(Event):
    event: (
        intent_specification_attribute_value_change_event_payload.IntentSpecificationAttributeValueChangeEventPayload
        | None
    ) = None
