# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_status_change_event_payload
from .event import Event


class IntentStatusChangeEvent(Event):
    event: intent_status_change_event_payload.IntentStatusChangeEventPayload | None = (
        None
    )
