# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import intent_ref, probe_intent


class IntentRefOrValue(RootModel[intent_ref.IntentRef | probe_intent.ProbeIntent]):
    root: Annotated[
        intent_ref.IntentRef | probe_intent.ProbeIntent,
        Field(discriminator='field_type'),
    ]
    """
    Intent Ref (if Intent already exists) or Value (if Intent be created or its details be presented)
    """
