# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_specification_delete_event_payload
from .event import Event


class IntentSpecificationDeleteEvent(Event):
    event: (
        intent_specification_delete_event_payload.IntentSpecificationDeleteEventPayload
        | None
    ) = None
