# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, Field

from . import json_ld_expression, time_period, turtle_expression
from .entity import Entity


class IntentReport(Entity):
    description: str | None = None
    """
    The description of the intent report.
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    intent: Annotated[
        intent_ref.IntentRef | probe_intent.ProbeIntent | None,
        Field(discriminator='field_type'),
    ] = None
    """
    Intent Ref (if Intent already exists) or Value (if Intent be created or its details be presented)
    """
    name: str | None = None
    """
    The name of the intent report.
    """
    expression: Annotated[
        json_ld_expression.JsonLdExpression | turtle_expression.TurtleExpression | None,
        Field(discriminator='field_type'),
    ] = None
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this intent report
    """
    field_type: Literal['IntentReport'] = Field(..., alias='@type')
