# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, Field

from . import (
    boolean_array_characteristic,
    boolean_characteristic,
    entity_ref,
    entity_relationship,
    integer_array_characteristic,
    integer_characteristic,
    json_ld_expression,
    number_array_characteristic,
    number_characteristic,
    object_array_characteristic,
    object_characteristic,
    related_party_ref_or_party_role_ref,
    string_array_characteristic,
    string_characteristic,
    time_period,
    turtle_expression,
)
from .entity import Entity


class Intent(Entity):
    description: str | None = None
    """
    The description of the intent.
    """
    valid_for: Annotated[time_period.TimePeriod | None, Field(alias='validFor')] = None
    is_bundle: Annotated[bool | None, Field(alias='isBundle')] = None
    """
    isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true).
    """
    priority: str | None = None
    """
    Can be used by intent owner to prioritize intents in an intent management system
    """
    status_change_date: Annotated[
        AwareDatetime | None, Field(alias='statusChangeDate')
    ] = None
    """
    A date time( DateTime). The date that the entity status changed to the current one
    """
    context: str | None = None
    """
    A string used to give a context to the intent
    """
    version: str | None = None
    """
    A field that identifies the specific version of an instance of an intent.
    """
    intent_specification: Annotated[
        entity_ref.EntityRef | None, Field(alias='intentSpecification')
    ] = None
    intent_relationship: Annotated[
        list[entity_relationship.EntityRelationship] | None,
        Field(alias='intentRelationship'),
    ] = None
    """
    A list of intents related to this intent
    """
    characteristic: (
        list[
            boolean_array_characteristic.BooleanArrayCharacteristic
            | boolean_characteristic.BooleanCharacteristic
            | integer_array_characteristic.IntegerArrayCharacteristic
            | integer_characteristic.IntegerCharacteristic
            | number_array_characteristic.NumberArrayCharacteristic
            | number_characteristic.NumberCharacteristic
            | object_array_characteristic.ObjectArrayCharacteristic
            | object_characteristic.ObjectCharacteristic
            | string_array_characteristic.StringArrayCharacteristic
            | string_characteristic.StringCharacteristic
        ]
        | None
    ) = None
    related_party: Annotated[
        list[related_party_ref_or_party_role_ref.RelatedPartyRefOrPartyRoleRef] | None,
        Field(alias='relatedParty'),
    ] = None
    attachment: (
        list[
            Annotated[
                attachment.Attachment | attachment_ref.AttachmentRef,
                Field(discriminator='field_type'),
            ]
        ]
        | None
    ) = None
    """
    Attachments that may be of relevance to this intent, such as picture, document, media
    """
    name: str | None = None
    """
    The name of the intent.
    """
    expression: Annotated[
        json_ld_expression.JsonLdExpression | turtle_expression.TurtleExpression | None,
        Field(discriminator='field_type'),
    ] = None
    creation_date: Annotated[AwareDatetime | None, Field(alias='creationDate')] = None
    """
    Date and time of the creation of this REST resource
    """
    last_update: Annotated[AwareDatetime | None, Field(alias='lastUpdate')] = None
    """
    Date and time of the last update of this REST resource
    """
    lifecycle_status: Annotated[str | None, Field(alias='lifecycleStatus')] = None
    """
    Used to indicate the current lifecycle status of this intent
    """
