# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from . import intent_report_create_event_payload
from .event import Event


class IntentReportCreateEvent(Event):
    event: intent_report_create_event_payload.IntentReportCreateEventPayload | None = (
        None
    )
