# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import probe_intent


class IntentAttributeValueChangeEventPayload(BaseModel):
    intent: Annotated[
        probe_intent.ProbeIntent | None, Field(discriminator='field_type')
    ] = None
