# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ._internal_2 import JsonLdExpressionValueMVO
from .intent_expression_mvo import IntentExpressionMVO


class JsonLdExpressionMVO(IntentExpressionMVO):
    expression_value: Annotated[
        JsonLdExpressionValueMVO, Field(alias='expressionValue')
    ]
    field_type: Literal['JsonLdExpression'] = Field(..., alias='@type')
