# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field

from . import op as op_1


class JsonPatch(BaseModel):
    op: op_1.Op
    """
    The operation to be performed
    """
    path: str
    """
    A JSON-Pointer
    """
    value: Any | None = None
    """
    The value to be used within the operations.
    """
    from_: Annotated[str | None, Field(alias='from')] = None
    """
    A string containing a JSON Pointer value.
    """
