# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ._internal_1 import JsonLdExpressionValueFVO
from .intent_expression_fvo import IntentExpressionFVO


class JsonLdExpressionFVO(IntentExpressionFVO):
    expression_value: Annotated[
        JsonLdExpressionValueFVO, Field(alias='expressionValue')
    ]
    field_type: Literal['JsonLdExpression'] = Field(..., alias='@type')
