# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from pydantic import RootModel

from . import json_patch


class JsonPatchOperations(RootModel[list[json_patch.JsonPatch]]):
    root: list[json_patch.JsonPatch]
    """
    JSONPatch Operations document as defined by RFC 6902
    """
