# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Any

from .characteristic_fvo import CharacteristicFVO


class ObjectCharacteristicFVO(CharacteristicFVO):
    value: dict[str, Any]
    """
    Value of the characteristic
    """
