# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Any

from .characteristic import Characteristic


class ObjectCharacteristic(Characteristic):
    value: dict[str, Any] | None = None
    """
    Value of the characteristic
    """
