# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .entity_ref import EntityRef


class PartyRoleRef(EntityRef):
    party_id: Annotated[str | None, Field(alias='partyId')] = None
    """
    The identifier of the engaged party that is linked to the PartyRole object.
    """
    party_name: Annotated[str | None, Field(alias='partyName')] = None
    """
    The name of the engaged party that is linked to the PartyRole object.
    """
