# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .entity_ref_mvo import EntityRefMVO


class PartyRefMVO(EntityRefMVO):
    pass
