# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import party_ref_mvo, party_role_ref_mvo


class PartyRefOrPartyRoleRefMVO(
    RootModel[party_ref_mvo.PartyRefMVO | party_role_ref_mvo.PartyRoleRefMVO]
):
    root: Annotated[
        party_ref_mvo.PartyRefMVO | party_role_ref_mvo.PartyRoleRefMVO,
        Field(discriminator='field_type'),
    ]
