# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import party_ref_fvo, party_role_ref_fvo


class PartyRefOrPartyRoleRefFVO(
    RootModel[party_ref_fvo.PartyRefFVO | party_role_ref_fvo.PartyRoleRefFVO]
):
    root: Annotated[
        party_ref_fvo.PartyRefFVO | party_role_ref_fvo.PartyRoleRefFVO,
        Field(discriminator='field_type'),
    ]
