# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from . import party_ref, party_role_ref


class PartyRefOrPartyRoleRef(
    RootModel[party_ref.PartyRef | party_role_ref.PartyRoleRef]
):
    root: Annotated[
        party_ref.PartyRef | party_role_ref.PartyRoleRef,
        Field(discriminator='field_type'),
    ]
