# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Literal

from pydantic import Field

from .intent import Intent


class ProbeIntent(Intent):
    field_type: Literal['ProbeIntent'] = Field(..., alias='@type')
