# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .extensible_mvo import ExtensibleMVO


class RelatedPartyRefOrPartyRoleRefMVO(ExtensibleMVO):
    role: str | None = None
    """
    Role played by the related party or party role in the context of the specific entity it is linked to. Such as 'initiator', 'customer',  'salesAgent', 'user'
    """
    party_or_party_role: Annotated[
        party_ref_mvo.PartyRefMVO | party_role_ref_mvo.PartyRoleRefMVO | None,
        Field(alias='partyOrPartyRole', discriminator='field_type'),
    ] = None
