# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .characteristic import Characteristic


class StringCharacteristic(Characteristic):
    value: str | None = None
    """
    Value of the characteristic
    """
