# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from .characteristic_mvo import CharacteristicMVO


class StringCharacteristicMVO(CharacteristicMVO):
    value: str | None = None
    """
    Value of the characteristic
    """
