# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class TargetEntitySchemaFVO(BaseModel):
    field_type: Annotated[str, Field(alias='@type')]
    """
    Class type of the target entity
    """
    field_schema_location: Annotated[str, Field(alias='@schemaLocation')]
    """
    This field provides a link to the schema describing the target entity
    """
