# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class TargetEntitySchemaMVO(BaseModel):
    field_schema_location: Annotated[str | None, Field(alias='@schemaLocation')] = None
    """
    This field provides a link to the schema describing the target entity
    """
