# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class TimePeriod(BaseModel):
    start_date_time: Annotated[
        AwareDatetime | None,
        Field(alias='startDateTime', examples=['1985-04-12T23:20:50.52Z']),
    ] = None
    """
    Start of the time period, using IETC-RFC-3339 format
    """
    end_date_time: Annotated[
        AwareDatetime | None,
        Field(alias='endDateTime', examples=['1985-04-12T23:20:50.52Z']),
    ] = None
    """
    End of the time period, using IETC-RFC-3339 format
    """
