# generated by datamodel-codegen:
#   filename:  TMF921_Intent_Management_v5.0.0.oas.yaml

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from .intent_expression import IntentExpression


class TurtleExpression(IntentExpression):
    expression_value: Annotated[str | None, Field(alias='expressionValue')] = None
    """
    Turtle Expression value is the ontology-encoded form of the Intent as Turtle RDF as defined in https://www.w3.org/TR/turtle/
    """
    field_type: Literal['TurtleExpression'] = Field(..., alias='@type')
